version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: healthcare-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare-analytics-app
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DB_URL=mongodb://mongodb:27017/healthcare
      - JWT_SECRET=${}
      - GROQ_API_KEY=${}
    depends_on:
      - mongodb

volumes:
  mongodb_data:
